
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define TILE_WIDTH 32
#define TILE_HEIGHT 16
#define H_TILES (SCREEN_WIDTH  / TILE_WIDTH)
#define V_TILES (SCREEN_HEIGHT / TILE_HEIGHT)
#define SCREEN_SIZE (SCREEN_WIDTH * SCREEN_HEIGHT)
